---

- name: Create/update data by looping through data center vars.
  ansible.builtin.include_tasks: loop_data_centers.yaml
  loop: "{{ fad_glb_data_centers }}"
  loop_control:
    loop_var: data_center
