---

- name: Create/update GLB Servers and Server Members.
  tags:
    - fad_glb_servers
  block:
    - name: Create/update GLB Servers and Server Members.
      ansible.builtin.include_tasks: 01-0-glb-servers.yaml
      loop: "{{ fad_glb_servers }}"
      loop_control:
        loop_var: glb_server
        label: "{{ glb_server.name }}"
